{
 "title": "PMetrium Native - Android",
 "time": { "from": "2022-06-22T08:12:25.634Z", "to": "2022-06-22T08:12:42.929Z" },
 "templating": {
  "list": [
   {
    "name": "space",
    "label": "Space",
    "query": "SHOW TAG VALUES FROM \"android.annotations\" WITH KEY = \"space\""
   },
   {
    "name": "group",
    "label": "Group",
    "query": "SELECT DISTINCT(\"group\") FROM (SELECT \"group\",\"text\" FROM \"android.annotations\" WHERE $timeFilter AND space=~ /$space/)"
   },
   {
    "name": "label",
    "label": "Label",
    "query": "SELECT DISTINCT(\"label\") FROM (SELECT \"label\",\"text\" FROM \"android.annotations\" WHERE $timeFilter AND space=~ /$space/ AND \"group\" =~ /$group/)   "
   },
   {
    "name": "androidVersion",
    "label": "AndroidVersion",
    "query": "SELECT DISTINCT(\"androidVersion\") FROM (SELECT \"androidVersion\",\"text\" FROM \"android.annotations\" WHERE $timeFilter AND space=~ /$space/ AND \"group\" =~ /$group/ AND label =~ /$label/)"
   },
   {
    "name": "deviceName",
    "label": "DeviceName",
    "query": "SELECT DISTINCT(\"deviceName\") FROM (SELECT \"deviceName\",\"text\" FROM \"android.annotations\" WHERE $timeFilter AND space=~ /$space/ AND \"group\" =~ /$group/ AND label =~ /$label/ AND androidVersion =~ /$androidVersion/) \t\t"
   },
   {
    "name": "device",
    "label": "Device",
    "query": "SELECT DISTINCT(\"device\") FROM (SELECT \"device\",\"text\" FROM \"android.annotations\" WHERE $timeFilter AND space=~ /$space/ AND \"group\" =~ /$group/ AND label =~ /$label/ AND androidVersion =~ /$androidVersion/ AND deviceName =~ /$deviceName/)"
   },
   { "name": "fill", "label": "Optimize query", "query": "null, none" }
  ]
 },
 "panels": [
  {
   "title": "CPU",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "alias": "CPU - Total",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT last(\"percentage\") FROM \"android.cpu.usage.total\" WHERE  $timeFilter AND space =~ /^$space/ AND \"group\" =~ /^$group/ AND label =~ /^$label/ AND androidVersion =~ /^$androidVersion/ AND deviceName =~ /^$deviceName/ AND device =~ /^$device/ GROUP BY time(1s) FILL($fill)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "CPU - App",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT last(\"percentage\") FROM \"android.cpu.usage.app\" WHERE $timeFilter AND space =~ /^$space/ AND \"group\" =~ /^$group/ AND label =~ /^$label/ AND androidVersion =~ /^$androidVersion/ AND deviceName =~ /^$deviceName/ AND device =~ /^$device/ GROUP BY time(1s) FILL($fill)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "RAM",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "alias": "RAM - Total",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT last(\"byte\") FROM \"android.ram.total\" WHERE $timeFilter AND space =~ /^$space/ AND \"group\" =~ /^$group/ AND label =~ /^$label/ AND androidVersion =~ /^$androidVersion/ AND deviceName =~ /^$deviceName/ AND device =~ /^$device/ GROUP BY time(1s) FILL($fill)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "RAM - Total Used",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT last(\"byte\") FROM \"android.ram.usage.total\" WHERE  $timeFilter AND space =~ /^$space/ AND \"group\" =~ /^$group/ AND label =~ /^$label/ AND androidVersion =~ /^$androidVersion/ AND deviceName =~ /^$deviceName/ AND device =~ /^$device/ GROUP BY time(1s) FILL($fill)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "RAM - App PSS",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT last(\"byte\") FROM \"android.ram.usage.app.pss\" WHERE $timeFilter AND space =~ /^$space/ AND \"group\" =~ /^$group/ AND label =~ /^$label/ AND androidVersion =~ /^$androidVersion/ AND deviceName =~ /^$deviceName/ AND device =~ /^$device/ GROUP BY time(1s) FILL($fill)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "RAM - App Private",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT last(\"byte\") FROM \"android.ram.usage.app.private\" WHERE $timeFilter AND space =~ /^$space/ AND \"group\" =~ /^$group/ AND label =~ /^$label/ AND androidVersion =~ /^$androidVersion/ AND deviceName =~ /^$deviceName/ AND device =~ /^$device/ GROUP BY time(1s) FILL($fill)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "NETWORK",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "alias": "Bytes/sec - transferred",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT last(\"byte\") FROM \"android.network.app.transferred\" WHERE $timeFilter AND space =~ /^$space/ AND \"group\" =~ /^$group/ AND label =~ /^$label/ AND androidVersion =~ /^$androidVersion/ AND deviceName =~ /^$deviceName/ AND device =~ /^$device/ GROUP BY time(1s) FILL($fill)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Bytes/sec - received",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT last(\"byte\") FROM \"android.network.app.received\" WHERE $timeFilter AND space =~ /^$space/ AND \"group\" =~ /^$group/ AND label =~ /^$label/ AND androidVersion =~ /^$androidVersion/ AND deviceName =~ /^$deviceName/ AND device =~ /^$device/ GROUP BY time(1s) FILL($fill)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "BATTERY",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "mamph" } },
   "targets": [
    {
     "alias": "mAh",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT last(\"mAh\") FROM \"android.battery.usage.app\" WHERE $timeFilter AND space =~ /^$space/ AND \"group\" =~ /^$group/ AND label =~ /^$label/ AND androidVersion =~ /^$androidVersion/ AND deviceName =~ /^$deviceName/ AND device =~ /^$device/ GROUP BY time(1s) FILL($fill)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "FRAMES",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "alias": "Rendered frames",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT last(\"count\") FROM \"android.frames.rendered\" WHERE $timeFilter AND space =~ /^$space/ AND \"group\" =~ /^$group/ AND label =~ /^$label/ AND androidVersion =~ /^$androidVersion/ AND deviceName =~ /^$deviceName/ AND device =~ /^$device/ GROUP BY time(1s) FILL($fill)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Janky frames",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT last(\"count\") FROM \"android.frames.janky\" WHERE $timeFilter AND space =~ /^$space/ AND \"group\" =~ /^$group/ AND label =~ /^$label/ AND androidVersion =~ /^$androidVersion/ AND deviceName =~ /^$deviceName/ AND device =~ /^$device/ GROUP BY time(1s) FILL($fill)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "LAST APPLICATION EVENTS",
   "type": "bargauge",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "$tag_event",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT last(\"latency\") FROM \"android.events.app\" WHERE  $timeFilter AND space =~ /^$space/ AND \"group\" =~ /^$group/ AND label =~ /^$label/ AND androidVersion =~ /^$androidVersion/ AND deviceName =~ /^$deviceName/ AND device =~ /^$device/ GROUP BY time(1s), event FILL($fill)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "APPLICATION EVENTS",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "alias": "$tag_event",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT last(\"latency\") FROM \"android.events.app\" WHERE $timeFilter AND space =~ /^$space/ AND \"group\" =~ /^$group/ AND label =~ /^$label/ AND androidVersion =~ /^$androidVersion/ AND deviceName =~ /^$deviceName/ AND device =~ /^$device/ GROUP BY time(1s), event FILL($fill)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  }
 ]
}