{
 "title": "PMetrium Native - IOS",
 "time": { "from": "2022-12-16T15:57:49.692Z", "to": "2022-12-16T15:58:14.761Z" },
 "templating": {
  "list": [
   {
    "name": "space",
    "label": "Space",
    "query": "SHOW TAG VALUES FROM \"ios.annotations\" WITH KEY = \"space\""
   },
   {
    "name": "group",
    "label": "Group",
    "query": "SELECT DISTINCT(\"group\") FROM (SELECT \"group\",\"text\" FROM \"ios.annotations\" WHERE $timeFilter AND space=~ /$space$/)"
   },
   {
    "name": "label",
    "label": "Label",
    "query": "SELECT DISTINCT(\"label\") FROM (SELECT \"label\",\"text\" FROM \"ios.annotations\" WHERE $timeFilter AND space=~ /$space$/ AND \"group\" =~ /$group$/)   "
   },
   {
    "name": "iosVersion",
    "label": "IOS_Version",
    "query": "SELECT DISTINCT(\"iosVersion\") FROM (SELECT \"iosVersion\",\"text\" FROM \"ios.annotations\" WHERE $timeFilter AND space=~ /$space$/ AND \"group\" =~ /$group$/ AND label =~ /$label$/)"
   },
   {
    "name": "deviceModel",
    "label": "DeviceModel",
    "query": "SELECT DISTINCT(\"deviceModel\") FROM (SELECT \"deviceModel\",\"text\" FROM \"ios.annotations\" WHERE $timeFilter AND space=~ /$space$/ AND \"group\" =~ /$group$/ AND label =~ /$label$/ AND iosVersion =~ /$iosVersion$/) \t\t"
   },
   {
    "name": "device",
    "query": "SELECT DISTINCT(\"device\") FROM (SELECT \"device\",\"text\" FROM \"ios.annotations\" WHERE $timeFilter AND space=~ /$space$/ AND \"group\" =~ /$group$/ AND label =~ /$label$/ AND iosVersion =~ /$iosVersion$/ AND deviceModel =~ /$deviceModel$/)"
   },
   {
    "name": "application",
    "label": "Application",
    "query": "SELECT DISTINCT(\"application\") FROM (SELECT \"application\",\"text\" FROM \"ios.annotations\" WHERE $timeFilter AND space=~ /$space$/ AND \"group\" =~ /$group$/ AND label =~ /$label$/ AND iosVersion =~ /$iosVersion$/ AND deviceModel =~ /$deviceModel$/ AND device =~ /$device$/)"
   },
   {
    "name": "event",
    "label": "Events",
    "query": "SELECT DISTINCT(\"text\") FROM (SELECT \"text\" FROM \"ios.annotations\" WHERE $timeFilter AND space=~ /$space$/ AND \"group\" =~ /$group$/ AND label =~ /$label$/ AND iosVersion =~ /$iosVersion$/ AND deviceModel =~ /$deviceModel$/ AND device =~ /$device$/ AND application =~ /$application$/ AND \"title\" !='[ Test STARTED ]' AND \"title\" !='[ Test FINISHED ]')"
   },
   {
    "name": "complexEvent",
    "label": "ComplexEvents",
    "query": "SELECT DISTINCT(\"text\") FROM (SELECT \"text\" FROM \"ios.annotations\" WHERE $timeFilter AND space=~ /$space$/ AND \"group\" =~ /$group$/ AND label =~ /$label$/ AND iosVersion =~ /$iosVersion$/ AND deviceModel =~ /$deviceModel$/ AND device =~ /$device$/ AND application =~ /$application$/)"
   }
  ]
 },
 "panels": [
  { "title": "System metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CPU",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "alias": "CPU - Total",
     "query": "SELECT percentage FROM \"ios.system.cpu\" WHERE $timeFilter AND space=~ /$space$/ AND \"group\" =~ /$group$/ AND label =~ /$label$/ AND iosVersion =~ /$iosVersion$/ AND deviceModel =~ /$deviceModel$/ AND device =~ /$device$/ AND application =~ /$application$/ "
    }
   ]
  },
  {
   "title": "RAM",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "alias": "RAN - Total Used",
     "query": "SELECT bytes FROM \"ios.system.ram\" WHERE $timeFilter AND space=~ /$space$/ AND \"group\" =~ /$group$/ AND label =~ /$label$/ AND iosVersion =~ /$iosVersion$/ AND deviceModel =~ /$deviceModel$/ AND device =~ /$device$/ AND application =~ /$application$/ "
    }
   ]
  },
  {
   "title": "DISK - Data",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "alias": "DISK - Read",
     "query": "SELECT bytes FROM \"ios.system.disk.data.read\" WHERE $timeFilter AND space=~ /$space$/ AND \"group\" =~ /$group$/ AND label =~ /$label$/ AND iosVersion =~ /$iosVersion$/ AND deviceModel =~ /$deviceModel$/ AND device =~ /$device$/ AND application =~ /$application$/ "
    },
    {
     "alias": "DISK - Write",
     "query": "SELECT bytes FROM \"ios.system.disk.data.written\" WHERE $timeFilter AND space=~ /$space$/ AND \"group\" =~ /$group$/ AND label =~ /$label$/ AND iosVersion =~ /$iosVersion$/ AND deviceModel =~ /$deviceModel$/ AND device =~ /$device$/ AND application =~ /$application$/ "
    }
   ]
  },
  {
   "title": "DISK - Operations",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "alias": "DISK - Read",
     "query": "SELECT count FROM \"ios.system.disk.ops.read\" WHERE $timeFilter AND space=~ /$space$/ AND \"group\" =~ /$group$/ AND label =~ /$label$/ AND iosVersion =~ /$iosVersion$/ AND deviceModel =~ /$deviceModel$/ AND device =~ /$device$/ AND application =~ /$application$/ "
    },
    {
     "alias": "DISK - Write",
     "query": "SELECT count FROM \"ios.system.disk.ops.written\" WHERE $timeFilter AND space=~ /$space$/ AND \"group\" =~ /$group$/ AND label =~ /$label$/ AND iosVersion =~ /$iosVersion$/ AND deviceModel =~ /$deviceModel$/ AND device =~ /$device$/ AND application =~ /$application$/ "
    }
   ]
  },
  {
   "title": "NETWORK - Data",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "alias": "NETWORK - Received",
     "query": "SELECT bytes FROM \"ios.system.network.data.read\" WHERE $timeFilter AND space=~ /$space$/ AND \"group\" =~ /$group$/ AND label =~ /$label$/ AND iosVersion =~ /$iosVersion$/ AND deviceModel =~ /$deviceModel$/ AND device =~ /$device$/ AND application =~ /$application$/ "
    },
    {
     "alias": "NETWORK - Sent",
     "query": "SELECT bytes FROM \"ios.system.network.data.sent\" WHERE $timeFilter AND space=~ /$space$/ AND \"group\" =~ /$group$/ AND label =~ /$label$/ AND iosVersion =~ /$iosVersion$/ AND deviceModel =~ /$deviceModel$/ AND device =~ /$device$/ AND application =~ /$application$/ "
    }
   ]
  },
  {
   "title": "NETWORK - Packets",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "alias": "NETWORK - Received",
     "query": "SELECT count FROM \"ios.system.network.packets.in\" WHERE $timeFilter AND space=~ /$space$/ AND \"group\" =~ /$group$/ AND label =~ /$label$/ AND iosVersion =~ /$iosVersion$/ AND deviceModel =~ /$deviceModel$/ AND device =~ /$device$/ AND application =~ /$application$/ "
    },
    {
     "alias": "NETWORK - Sent",
     "query": "SELECT count FROM \"ios.system.network.packets.out\" WHERE $timeFilter AND space=~ /$space$/ AND \"group\" =~ /$group$/ AND label =~ /$label$/ AND iosVersion =~ /$iosVersion$/ AND deviceModel =~ /$deviceModel$/ AND device =~ /$device$/ AND application =~ /$application$/ "
    }
   ]
  },
  {
   "title": "FPS",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "alias": "FPS",
     "query": "SELECT count FROM \"ios.system.fps\" WHERE $timeFilter AND space=~ /$space$/ AND \"group\" =~ /$group$/ AND label =~ /$label$/ AND iosVersion =~ /$iosVersion$/ AND deviceModel =~ /$deviceModel$/ AND device =~ /$device$/ AND application =~ /$application$/ "
    }
   ]
  },
  {
   "title": "GPU",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "alias": "GPU - Utilization",
     "query": "SELECT  percentage FROM \"ios.system.gpu\" WHERE $timeFilter AND space=~ /$space$/ AND \"group\" =~ /$group$/ AND label =~ /$label$/ AND iosVersion =~ /$iosVersion$/ AND deviceModel =~ /$deviceModel$/ AND device =~ /$device$/ AND application =~ /$application$/ "
    }
   ]
  },
  { "title": "Application metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 } },
  {
   "title": "CPU",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "alias": "CPU - App",
     "query": "SELECT percentage FROM \"ios.app.cpu\" WHERE $timeFilter AND space=~ /$space$/ AND \"group\" =~ /$group$/ AND label =~ /$label$/ AND iosVersion =~ /$iosVersion$/ AND deviceModel =~ /$deviceModel$/ AND device =~ /$device$/ AND application =~ /$application$/"
    }
   ]
  },
  {
   "title": "Ram",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "alias": "RAM - App",
     "query": "SELECT bytes FROM \"ios.app.ram\" WHERE $timeFilter AND space=~ /$space$/ AND \"group\" =~ /$group$/ AND label =~ /$label$/ AND iosVersion =~ /$iosVersion$/ AND deviceModel =~ /$deviceModel$/ AND device =~ /$device$/ AND application =~ /$application$/"
    }
   ]
  },
  {
   "title": "NETWORK - Data",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "alias": "NETWORK - App Received",
     "query": "SELECT bytes FROM \"ios.app.network.data.rx\" WHERE $timeFilter AND space=~ /$space$/ AND \"group\" =~ /$group$/ AND label =~ /$label$/ AND iosVersion =~ /$iosVersion$/ AND deviceModel =~ /$deviceModel$/ AND device =~ /$device$/ AND application =~ /$application$/\n"
    },
    {
     "alias": "NETWORK - App Sent",
     "query": "SELECT bytes FROM \"ios.app.network.data.tx\" WHERE $timeFilter AND space=~ /$space$/ AND \"group\" =~ /$group$/ AND label =~ /$label$/ AND iosVersion =~ /$iosVersion$/ AND deviceModel =~ /$deviceModel$/ AND device =~ /$device$/ AND application =~ /$application$/\n"
    }
   ]
  },
  {
   "title": "NETWORK - Packets",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "alias": "NETWORK - App Received",
     "query": "SELECT count FROM \"ios.app.network.packets.in\" WHERE $timeFilter AND space=~ /$space$/ AND \"group\" =~ /$group$/ AND label =~ /$label$/ AND iosVersion =~ /$iosVersion$/ AND deviceModel =~ /$deviceModel$/ AND device =~ /$device$/ AND application =~ /$application$/\n"
    },
    {
     "alias": "NETWORK - App Sent",
     "query": "SELECT count FROM \"ios.app.network.packets.out\" WHERE $timeFilter AND space=~ /$space$/ AND \"group\" =~ /$group$/ AND label =~ /$label$/ AND iosVersion =~ /$iosVersion$/ AND deviceModel =~ /$deviceModel$/ AND device =~ /$device$/ AND application =~ /$application$/\n"
    }
   ]
  },
  {
   "title": "APPLICATION EVENTS",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "alias": "$tag_event",
     "query": "SELECT latency FROM \"ios.events.app\" WHERE $timeFilter AND space =~ /^$space$/ AND \"group\" =~ /^$group$/ AND label =~ /^$label$/ AND iosVersion =~ /^$iosVersion$/ AND deviceModel =~ /^$deviceModel$/ AND device =~ /^$device$/ AND application =~ /^$application$/ AND event =~ /.*$complexEvent.*/ GROUP BY event"
    }
   ]
  }
 ]
}