{
 "title": "PMetrium Native - Android",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "space",
    "label": "Space",
    "query": "SHOW TAG VALUES FROM \"android.annotations\" WITH KEY = \"space\""
   },
   {
    "name": "group",
    "label": "Group",
    "query": "SELECT DISTINCT(\"group\") FROM (SELECT \"group\",\"text\" FROM \"android.annotations\" WHERE $timeFilter AND space=~ /$space$/)"
   },
   {
    "name": "label",
    "label": "Label",
    "query": "SELECT DISTINCT(\"label\") FROM (SELECT \"label\",\"text\" FROM \"android.annotations\" WHERE $timeFilter AND space=~ /$space$/ AND \"group\" =~ /$group$/)   "
   },
   {
    "name": "androidVersion",
    "label": "AndroidVersion",
    "query": "SELECT DISTINCT(\"androidVersion\") FROM (SELECT \"androidVersion\",\"text\" FROM \"android.annotations\" WHERE $timeFilter AND space=~ /$space$/ AND \"group\" =~ /$group$/ AND label =~ /$label$/)"
   },
   {
    "name": "deviceName",
    "label": "DeviceName",
    "query": "SELECT DISTINCT(\"deviceName\") FROM (SELECT \"deviceName\",\"text\" FROM \"android.annotations\" WHERE $timeFilter AND space=~ /$space$/ AND \"group\" =~ /$group$/ AND label =~ /$label$/ AND androidVersion =~ /$androidVersion$/) \t\t"
   },
   {
    "name": "device",
    "label": "Device",
    "query": "SELECT DISTINCT(\"device\") FROM (SELECT \"device\",\"text\" FROM \"android.annotations\" WHERE $timeFilter AND space=~ /$space$/ AND \"group\" =~ /$group$/ AND label =~ /$label$/ AND androidVersion =~ /$androidVersion$/ AND deviceName =~ /$deviceName$/)"
   },
   {
    "name": "application",
    "label": "Application",
    "query": "SELECT DISTINCT(\"application\") FROM (SELECT \"application\",\"text\" FROM \"android.annotations\" WHERE $timeFilter AND space=~ /$space$/ AND \"group\" =~ /$group$/ AND label =~ /$label$/ AND androidVersion =~ /$androidVersion$/ AND deviceName =~ /$deviceName$/ AND device =~ /$device$/)"
   },
   {
    "name": "event",
    "label": "Events",
    "query": "SELECT DISTINCT(\"text\") FROM (SELECT \"text\" FROM \"android.annotations\" WHERE $timeFilter AND space=~ /$space$/ AND \"group\" =~ /$group$/ AND label =~ /$label$/ AND androidVersion =~ /$androidVersion$/ AND deviceName =~ /$deviceName$/ AND device =~ /$device$/ AND application =~ /$application$/ AND \"title\" !='[ Test STARTED ]' AND \"title\" !='[ Test FINISHED ]')"
   },
   {
    "name": "complexEvent",
    "label": "ComplexEvents",
    "query": "SELECT DISTINCT(\"text\") FROM (SELECT \"text\" FROM \"android.annotations\" WHERE $timeFilter AND space=~ /$space$/ AND \"group\" =~ /$group$/ AND label =~ /$label$/ AND androidVersion =~ /$androidVersion$/ AND deviceName =~ /$deviceName$/ AND device =~ /$device$/ AND application =~ /$application$/)"
   },
   {
    "name": "groupTime",
    "label": "GroupTime",
    "query": "1ms,10ms,100ms,500ms,1s,5s,10s,30s,1m,5m,10m"
   },
   { "name": "fill", "label": "OptimiseQuery", "query": "null,none" }
  ]
 },
 "panels": [
  {
   "title": "CPU",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "alias": "CPU - Total",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT mean(percentage) FROM \"android.cpu.usage.total\" WHERE  $timeFilter AND space =~ /^$space$/ AND \"group\" =~ /^$group$/ AND label =~ /^$label$/ AND androidVersion =~ /^$androidVersion$/ AND deviceName =~ /^$deviceName$/ AND device =~ /^$device$/ AND application =~ /^$application$/ GROUP BY time($groupTime) FILL($fill)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "CPU - App",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT mean(percentage) FROM \"android.cpu.usage.app\" WHERE $timeFilter AND space =~ /^$space$/ AND \"group\" =~ /^$group$/ AND label =~ /^$label$/ AND androidVersion =~ /^$androidVersion$/ AND deviceName =~ /^$deviceName$/ AND device =~ /^$device$/ AND application =~ /^$application$/ GROUP BY time($groupTime) FILL($fill)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "RAM",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "alias": "RAM - Total",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT mean(byte) FROM \"android.ram.total\" WHERE $timeFilter AND space =~ /^$space$/ AND \"group\" =~ /^$group$/ AND label =~ /^$label$/ AND androidVersion =~ /^$androidVersion$/ AND deviceName =~ /^$deviceName$/ AND device =~ /^$device$/ AND application =~ /^$application$/ GROUP BY time($groupTime) FILL($fill)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "RAM - Total Used",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT mean(byte) FROM \"android.ram.usage.total\" WHERE  $timeFilter AND space =~ /^$space$/ AND \"group\" =~ /^$group$/ AND label =~ /^$label$/ AND androidVersion =~ /^$androidVersion$/ AND deviceName =~ /^$deviceName$/ AND device =~ /^$device$/ AND application =~ /^$application$/ GROUP BY time($groupTime) FILL($fill)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "RAM - App PSS",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT mean(byte) FROM \"android.ram.usage.app.pss\" WHERE $timeFilter AND space =~ /^$space$/ AND \"group\" =~ /^$group$/ AND label =~ /^$label$/ AND androidVersion =~ /^$androidVersion$/ AND deviceName =~ /^$deviceName$/ AND device =~ /^$device$/ AND application =~ /^$application$/ GROUP BY time($groupTime) FILL($fill)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "RAM - App Private",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT mean(byte) FROM \"android.ram.usage.app.private\" WHERE $timeFilter AND space =~ /^$space/ AND \"group\" =~ /^$group/ AND label =~ /^$label/ AND androidVersion =~ /^$androidVersion/ AND deviceName =~ /^$deviceName/ AND device =~ /^$device/ AND application =~ /^$application/ GROUP BY time($groupTime) FILL($fill)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "NETWORK -  Usage bytes/sec",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "alias": "Wi-Fi TX bytes/sec - Total",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT mean(byte) FROM \"android.network.wifi.speed.total.tx\" WHERE $timeFilter AND space =~ /^$space$/ AND \"group\" =~ /^$group$/ AND label =~ /^$label$/ AND androidVersion =~ /^$androidVersion$/ AND deviceName =~ /^$deviceName$/ AND device =~ /^$device$/ AND application =~ /^$application$/ GROUP BY time($groupTime) FILL($fill)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Wi-Fi RX bytes/sec - Total",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT mean(byte) FROM \"android.network.wifi.speed.total.rx\" WHERE $timeFilter AND space =~ /^$space$/ AND \"group\" =~ /^$group$/ AND label =~ /^$label$/ AND androidVersion =~ /^$androidVersion$/ AND deviceName =~ /^$deviceName$/ AND device =~ /^$device$/ AND application =~ /^$application$/ GROUP BY time($groupTime) FILL($fill)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Wi-Fi TX bytes/sec - App",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT mean(byte) FROM \"android.network.wifi.speed.app.tx\" WHERE $timeFilter AND space =~ /^$space$/ AND \"group\" =~ /^$group$/ AND label =~ /^$label$/ AND androidVersion =~ /^$androidVersion$/ AND deviceName =~ /^$deviceName$/ AND device =~ /^$device$/ AND application =~ /^$application$/ GROUP BY time($groupTime) FILL($fill)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Wi-Fi RX bytes/sec - App",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT mean(byte) FROM \"android.network.wifi.speed.app.rx\" WHERE $timeFilter AND space =~ /^$space$/ AND \"group\" =~ /^$group$/ AND label =~ /^$label$/ AND androidVersion =~ /^$androidVersion$/ AND deviceName =~ /^$deviceName$/ AND device =~ /^$device$/ AND application =~ /^$application$/ GROUP BY time($groupTime) FILL($fill)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Mobile TX bytes/sec - Total",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT mean(byte) FROM \"android.network.mobile.speed.total.tx\" WHERE $timeFilter AND space =~ /^$space$/ AND \"group\" =~ /^$group$/ AND label =~ /^$label$/ AND androidVersion =~ /^$androidVersion$/ AND deviceName =~ /^$deviceName$/ AND device =~ /^$device$/ AND application =~ /^$application$/ GROUP BY time($groupTime) FILL($fill)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Mobile RX bytes/sec - Total",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT mean(byte) FROM \"android.network.mobile.speed.total.rx\" WHERE $timeFilter AND space =~ /^$space$/ AND \"group\" =~ /^$group$/ AND label =~ /^$label$/ AND androidVersion =~ /^$androidVersion$/ AND deviceName =~ /^$deviceName$/ AND device =~ /^$device$/ AND application =~ /^$application$/ GROUP BY time($groupTime) FILL($fill)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Mobile TX bytes/sec - App",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT mean(byte) FROM \"android.network.mobile.speed.app.tx\" WHERE $timeFilter AND space =~ /^$space$/ AND \"group\" =~ /^$group$/ AND label =~ /^$label$/ AND androidVersion =~ /^$androidVersion$/ AND deviceName =~ /^$deviceName$/ AND device =~ /^$device$/ AND application =~ /^$application$/ GROUP BY time($groupTime) FILL($fill)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Mobile RX bytes/sec - App",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT mean(byte) FROM \"android.network.mobile.speed.app.rx\" WHERE $timeFilter AND space =~ /^$space$/ AND \"group\" =~ /^$group$/ AND label =~ /^$label$/ AND androidVersion =~ /^$androidVersion$/ AND deviceName =~ /^$deviceName$/ AND device =~ /^$device$/ AND application =~ /^$application$/ GROUP BY time($groupTime) FILL($fill)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "NETWORK - All bytes",
   "type": "timeseries",
   "description": "The sum of bytes RX and TX by the system and the app from the beginning of the test till the end",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "alias": "Wi-Fi TX bytes - Total",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT mean(byte) FROM \"android.network.wifi.all.total.tx\" WHERE $timeFilter AND space =~ /^$space$/ AND \"group\" =~ /^$group$/ AND label =~ /^$label$/ AND androidVersion =~ /^$androidVersion$/ AND deviceName =~ /^$deviceName$/ AND device =~ /^$device$/ AND application =~ /^$application$/ GROUP BY time($groupTime) FILL($fill)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Wi-Fi RX bytes - Total",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT mean(byte) FROM \"android.network.wifi.all.total.rx\" WHERE $timeFilter AND space =~ /^$space$/ AND \"group\" =~ /^$group$/ AND label =~ /^$label$/ AND androidVersion =~ /^$androidVersion$/ AND deviceName =~ /^$deviceName$/ AND device =~ /^$device$/ AND application =~ /^$application$/ GROUP BY time($groupTime) FILL($fill)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Wi-Fi TX bytes - App",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT mean(byte) FROM \"android.network.wifi.all.app.tx\" WHERE $timeFilter AND space =~ /^$space$/ AND \"group\" =~ /^$group$/ AND label =~ /^$label$/ AND androidVersion =~ /^$androidVersion$/ AND deviceName =~ /^$deviceName$/ AND device =~ /^$device$/ AND application =~ /^$application$/ GROUP BY time($groupTime) FILL($fill)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Wi-Fi RX bytes - App",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT mean(byte) FROM \"android.network.wifi.all.app.rx\" WHERE $timeFilter AND space =~ /^$space$/ AND \"group\" =~ /^$group$/ AND label =~ /^$label$/ AND androidVersion =~ /^$androidVersion$/ AND deviceName =~ /^$deviceName$/ AND device =~ /^$device$/ AND application =~ /^$application$/ GROUP BY time($groupTime) FILL($fill)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Mobile TX bytes - Total",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT mean(byte) FROM \"android.network.mobile.all.total.tx\" WHERE $timeFilter AND space =~ /^$space$/ AND \"group\" =~ /^$group$/ AND label =~ /^$label$/ AND androidVersion =~ /^$androidVersion$/ AND deviceName =~ /^$deviceName$/ AND device =~ /^$device$/ AND application =~ /^$application$/ GROUP BY time($groupTime) FILL($fill)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Mobile RX bytes - Total",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT mean(byte) FROM \"android.network.mobile.all.total.rx\" WHERE $timeFilter AND space =~ /^$space$/ AND \"group\" =~ /^$group$/ AND label =~ /^$label$/ AND androidVersion =~ /^$androidVersion$/ AND deviceName =~ /^$deviceName$/ AND device =~ /^$device$/ AND application =~ /^$application$/ GROUP BY time($groupTime) FILL($fill)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Mobile TX bytes - App",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT mean(byte) FROM \"android.network.mobile.all.app.tx\" WHERE $timeFilter AND space =~ /^$space$/ AND \"group\" =~ /^$group$/ AND label =~ /^$label$/ AND androidVersion =~ /^$androidVersion$/ AND deviceName =~ /^$deviceName$/ AND device =~ /^$device$/ AND application =~ /^$application$/ GROUP BY time($groupTime) FILL($fill)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Mobile RX bytes - App",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT mean(byte) FROM \"android.network.mobile.all.app.rx\" WHERE $timeFilter AND space =~ /^$space$/ AND \"group\" =~ /^$group$/ AND label =~ /^$label$/ AND androidVersion =~ /^$androidVersion$/ AND deviceName =~ /^$deviceName$/ AND device =~ /^$device$/ AND application =~ /^$application$/ GROUP BY time($groupTime) FILL($fill)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "BATTERY",
   "type": "timeseries",
   "description": "Used by application only!",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "mamph" } },
   "targets": [
    {
     "alias": "mAh",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT mean(mAh) FROM \"android.battery.usage.app\" WHERE $timeFilter AND space =~ /^$space$/ AND \"group\" =~ /^$group$/ AND label =~ /^$label$/ AND androidVersion =~ /^$androidVersion$/ AND deviceName =~ /^$deviceName$/ AND device =~ /^$device$/ AND application =~ /^$application$/ GROUP BY time($groupTime) FILL($fill)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "FRAMES",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "alias": "Rendered frames",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT mean(count) FROM \"android.frames.rendered\" WHERE $timeFilter AND space =~ /^$space$/ AND \"group\" =~ /^$group$/ AND label =~ /^$label$/ AND androidVersion =~ /^$androidVersion$/ AND deviceName =~ /^$deviceName$/ AND device =~ /^$device$/ AND application =~ /^$application$/ GROUP BY time($groupTime) FILL($fill)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Janky frames",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT mean(count) FROM \"android.frames.janky\" WHERE $timeFilter AND space =~ /^$space$/ AND \"group\" =~ /^$group$/ AND label =~ /^$label$/ AND androidVersion =~ /^$androidVersion$/ AND deviceName =~ /^$deviceName$/ AND device =~ /^$device$/ AND application =~ /^$application$/ GROUP BY time($groupTime) FILL($fill)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "APPLICATION EVENTS",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "alias": "$tag_event",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT mean(latency) FROM \"android.events.app\" WHERE $timeFilter AND space =~ /^$space$/ AND \"group\" =~ /^$group$/ AND label =~ /^$label$/ AND androidVersion =~ /^$androidVersion$/ AND deviceName =~ /^$deviceName$/ AND device =~ /^$device$/ AND application =~ /^$application$/ AND event =~ /.*$complexEvent.*/ GROUP BY time($groupTime), event FILL($fill)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  }
 ]
}